name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        py-version: [3.9]
        
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py-version }}
        
